spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springBoot01
    username: root
    password: root
server:
  port: 9090
  servlet:
    context-path: /spring-demo
    session:
      timeout: PT5H

